### ISSUE TITLE
Meetup November/December 2023

### ISSUE THREAD

**Issue by hanneoberman** [r-lgbtq/organisation#2]
## Set up

- [x] Decide date and time, preferably at least two weeks in advance: Nov 15th, 5 PM UK time (UCT)
- [x] Decide purpose of meetup and whether there'll be any activity, e.g. show and tell or a speaker:  Buddy system launch, show and tell
- [x] Create event on Zoom, using Forwards account: <https://zoom.us> (Ella)
    - Make sure that registration is required
- [x] Create image to share (Ella)
- [x] ~~Add to RainbowR website (once events page is created!)~~

## Promote

- [x] RainbowR on Mastodon: <https://tech.lgbt/@rainbowR> (Hanne)
- [x] RainbowR Slack: <https://rainbowr.slack.com> (Hanne)
- [x] Forwards Slack: <https://rforwards.slack.com> (Ella)
- [x] Email list (Ella)
- [x] Boost or send our reminder the day before (Hanne)

## Prepare for meetup

- [x] Create an etherpad with outline and for writing/sharing any notes during the meeting (Hanne)
  - simply create with a new URL in format <https://developer.r-project.org/etherpad/p/YYYY-MM-DD-rainbowR> (just update date!)
  - see e.g. <https://developer.r-project.org/etherpad/p/2022-11-01-rainbowR>
  - https://developer.r-project.org/etherpad/p/2023-11-15-rainbowR
  
## After meetup

- [x] back up etherpad notes by copying into a new .md file in <https://github.com/r-lgbtq/meeting-notes> (this is a private repo)

**Comment by hanneoberman** [comment]
Bit late, but share spooktober data quests? https://github.com/ubvu/OpenScienceAgainstHumanity#playing-online

**Comment by EllaKaye** [comment]
Ooh, that looks fun! It could be a cool thing for you to share in the show-and-tell, if you've had fun playing it yourself. I'd be a bit wary of sharing it officially from rainbowR because, as far as I can tell, it's not quite R or queer enough. Also, it seems aimed at researchers and I've heard from a couple of non-academic members of the group previously that they find overtly academic stuff a bit alienating and it makes them question if rainbowR is right for them.
